# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bibek/OpenIFEM/OpenIFEM-source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bibek/OpenIFEM/OpenIFEM-source

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bibek/OpenIFEM/OpenIFEM-source/CMakeFiles /home/bibek/OpenIFEM/OpenIFEM-source/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bibek/OpenIFEM/OpenIFEM-source/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openifem

# Build rule for target.
openifem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 openifem
.PHONY : openifem

# fast build rule for target.
openifem/fast:
	$(MAKE) $(MAKESILENT) -f source/CMakeFiles/openifem.dir/build.make source/CMakeFiles/openifem.dir/build
.PHONY : openifem/fast

#=============================================================================
# Target rules for targets named solid_beam_bending_mpi_shared_NeoHookean

# Build rule for target.
solid_beam_bending_mpi_shared_NeoHookean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_beam_bending_mpi_shared_NeoHookean
.PHONY : solid_beam_bending_mpi_shared_NeoHookean

# fast build rule for target.
solid_beam_bending_mpi_shared_NeoHookean/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_beam_bending_mpi_shared_NeoHookean.dir/build.make tests/CMakeFiles/solid_beam_bending_mpi_shared_NeoHookean.dir/build
.PHONY : solid_beam_bending_mpi_shared_NeoHookean/fast

#=============================================================================
# Target rules for targets named solid_beam_bending_mpi_shared_linearelastic

# Build rule for target.
solid_beam_bending_mpi_shared_linearelastic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_beam_bending_mpi_shared_linearelastic
.PHONY : solid_beam_bending_mpi_shared_linearelastic

# fast build rule for target.
solid_beam_bending_mpi_shared_linearelastic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_beam_bending_mpi_shared_linearelastic.dir/build.make tests/CMakeFiles/solid_beam_bending_mpi_shared_linearelastic.dir/build
.PHONY : solid_beam_bending_mpi_shared_linearelastic/fast

#=============================================================================
# Target rules for targets named solid_beam_bending_mpi_NeoHookean

# Build rule for target.
solid_beam_bending_mpi_NeoHookean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_beam_bending_mpi_NeoHookean
.PHONY : solid_beam_bending_mpi_NeoHookean

# fast build rule for target.
solid_beam_bending_mpi_NeoHookean/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_beam_bending_mpi_NeoHookean.dir/build.make tests/CMakeFiles/solid_beam_bending_mpi_NeoHookean.dir/build
.PHONY : solid_beam_bending_mpi_NeoHookean/fast

#=============================================================================
# Target rules for targets named solid_beam_bending_mpi_linearelastic

# Build rule for target.
solid_beam_bending_mpi_linearelastic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_beam_bending_mpi_linearelastic
.PHONY : solid_beam_bending_mpi_linearelastic

# fast build rule for target.
solid_beam_bending_mpi_linearelastic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_beam_bending_mpi_linearelastic.dir/build.make tests/CMakeFiles/solid_beam_bending_mpi_linearelastic.dir/build
.PHONY : solid_beam_bending_mpi_linearelastic/fast

#=============================================================================
# Target rules for targets named fsi_gravity_mpi

# Build rule for target.
fsi_gravity_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsi_gravity_mpi
.PHONY : fsi_gravity_mpi

# fast build rule for target.
fsi_gravity_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fsi_gravity_mpi.dir/build.make tests/CMakeFiles/fsi_gravity_mpi.dir/build
.PHONY : fsi_gravity_mpi/fast

#=============================================================================
# Target rules for targets named fsi_contact_model_mpi

# Build rule for target.
fsi_contact_model_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsi_contact_model_mpi
.PHONY : fsi_contact_model_mpi

# fast build rule for target.
fsi_contact_model_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fsi_contact_model_mpi.dir/build.make tests/CMakeFiles/fsi_contact_model_mpi.dir/build
.PHONY : fsi_contact_model_mpi/fast

#=============================================================================
# Target rules for targets named fsi_cavity

# Build rule for target.
fsi_cavity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsi_cavity
.PHONY : fsi_cavity

# fast build rule for target.
fsi_cavity/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fsi_cavity.dir/build.make tests/CMakeFiles/fsi_cavity.dir/build
.PHONY : fsi_cavity/fast

#=============================================================================
# Target rules for targets named fluid_pressure_driven_mpi_insim_supg

# Build rule for target.
fluid_pressure_driven_mpi_insim_supg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_pressure_driven_mpi_insim_supg
.PHONY : fluid_pressure_driven_mpi_insim_supg

# fast build rule for target.
fluid_pressure_driven_mpi_insim_supg/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_pressure_driven_mpi_insim_supg.dir/build.make tests/CMakeFiles/fluid_pressure_driven_mpi_insim_supg.dir/build
.PHONY : fluid_pressure_driven_mpi_insim_supg/fast

#=============================================================================
# Target rules for targets named fluid_pressure_driven

# Build rule for target.
fluid_pressure_driven: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_pressure_driven
.PHONY : fluid_pressure_driven

# fast build rule for target.
fluid_pressure_driven/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_pressure_driven.dir/build.make tests/CMakeFiles/fluid_pressure_driven.dir/build
.PHONY : fluid_pressure_driven/fast

#=============================================================================
# Target rules for targets named fluid_cylinder_insimex

# Build rule for target.
fluid_cylinder_insimex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_cylinder_insimex
.PHONY : fluid_cylinder_insimex

# fast build rule for target.
fluid_cylinder_insimex/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_cylinder_insimex.dir/build.make tests/CMakeFiles/fluid_cylinder_insimex.dir/build
.PHONY : fluid_cylinder_insimex/fast

#=============================================================================
# Target rules for targets named acoustic_pml

# Build rule for target.
acoustic_pml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acoustic_pml
.PHONY : acoustic_pml

# fast build rule for target.
acoustic_pml/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/acoustic_pml.dir/build.make tests/CMakeFiles/acoustic_pml.dir/build
.PHONY : acoustic_pml/fast

#=============================================================================
# Target rules for targets named fluid_pipe

# Build rule for target.
fluid_pipe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_pipe
.PHONY : fluid_pipe

# fast build rule for target.
fluid_pipe/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_pipe.dir/build.make tests/CMakeFiles/fluid_pipe.dir/build
.PHONY : fluid_pipe/fast

#=============================================================================
# Target rules for targets named fluid_cylinder_mpi_scnsim

# Build rule for target.
fluid_cylinder_mpi_scnsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_cylinder_mpi_scnsim
.PHONY : fluid_cylinder_mpi_scnsim

# fast build rule for target.
fluid_cylinder_mpi_scnsim/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_cylinder_mpi_scnsim.dir/build.make tests/CMakeFiles/fluid_cylinder_mpi_scnsim.dir/build
.PHONY : fluid_cylinder_mpi_scnsim/fast

#=============================================================================
# Target rules for targets named fluid_pipe_mpi

# Build rule for target.
fluid_pipe_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_pipe_mpi
.PHONY : fluid_pipe_mpi

# fast build rule for target.
fluid_pipe_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_pipe_mpi.dir/build.make tests/CMakeFiles/fluid_pipe_mpi.dir/build
.PHONY : fluid_pipe_mpi/fast

#=============================================================================
# Target rules for targets named fluid_gravity

# Build rule for target.
fluid_gravity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_gravity
.PHONY : fluid_gravity

# fast build rule for target.
fluid_gravity/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_gravity.dir/build.make tests/CMakeFiles/fluid_gravity.dir/build
.PHONY : fluid_gravity/fast

#=============================================================================
# Target rules for targets named fsi_leaflet_mpi

# Build rule for target.
fsi_leaflet_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsi_leaflet_mpi
.PHONY : fsi_leaflet_mpi

# fast build rule for target.
fsi_leaflet_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fsi_leaflet_mpi.dir/build.make tests/CMakeFiles/fsi_leaflet_mpi.dir/build
.PHONY : fsi_leaflet_mpi/fast

#=============================================================================
# Target rules for targets named solid_beam_bending_NeoHookean

# Build rule for target.
solid_beam_bending_NeoHookean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_beam_bending_NeoHookean
.PHONY : solid_beam_bending_NeoHookean

# fast build rule for target.
solid_beam_bending_NeoHookean/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_beam_bending_NeoHookean.dir/build.make tests/CMakeFiles/solid_beam_bending_NeoHookean.dir/build
.PHONY : solid_beam_bending_NeoHookean/fast

#=============================================================================
# Target rules for targets named fluid_cylinder

# Build rule for target.
fluid_cylinder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_cylinder
.PHONY : fluid_cylinder

# fast build rule for target.
fluid_cylinder/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_cylinder.dir/build.make tests/CMakeFiles/fluid_cylinder.dir/build
.PHONY : fluid_cylinder/fast

#=============================================================================
# Target rules for targets named fsi_leaflet

# Build rule for target.
fsi_leaflet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsi_leaflet
.PHONY : fsi_leaflet

# fast build rule for target.
fsi_leaflet/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fsi_leaflet.dir/build.make tests/CMakeFiles/fsi_leaflet.dir/build
.PHONY : fsi_leaflet/fast

#=============================================================================
# Target rules for targets named acoustic_duct_wave_mpi

# Build rule for target.
acoustic_duct_wave_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acoustic_duct_wave_mpi
.PHONY : acoustic_duct_wave_mpi

# fast build rule for target.
acoustic_duct_wave_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/acoustic_duct_wave_mpi.dir/build.make tests/CMakeFiles/acoustic_duct_wave_mpi.dir/build
.PHONY : acoustic_duct_wave_mpi/fast

#=============================================================================
# Target rules for targets named fluid_plane_wall_driven_mpi_insim_supg

# Build rule for target.
fluid_plane_wall_driven_mpi_insim_supg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_plane_wall_driven_mpi_insim_supg
.PHONY : fluid_plane_wall_driven_mpi_insim_supg

# fast build rule for target.
fluid_plane_wall_driven_mpi_insim_supg/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_plane_wall_driven_mpi_insim_supg.dir/build.make tests/CMakeFiles/fluid_plane_wall_driven_mpi_insim_supg.dir/build
.PHONY : fluid_plane_wall_driven_mpi_insim_supg/fast

#=============================================================================
# Target rules for targets named fsi_gravity

# Build rule for target.
fsi_gravity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsi_gravity
.PHONY : fsi_gravity

# fast build rule for target.
fsi_gravity/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fsi_gravity.dir/build.make tests/CMakeFiles/fsi_gravity.dir/build
.PHONY : fsi_gravity/fast

#=============================================================================
# Target rules for targets named fsi_benchmark

# Build rule for target.
fsi_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsi_benchmark
.PHONY : fsi_benchmark

# fast build rule for target.
fsi_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fsi_benchmark.dir/build.make tests/CMakeFiles/fsi_benchmark.dir/build
.PHONY : fsi_benchmark/fast

#=============================================================================
# Target rules for targets named acoustic_duct_wave

# Build rule for target.
acoustic_duct_wave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acoustic_duct_wave
.PHONY : acoustic_duct_wave

# fast build rule for target.
acoustic_duct_wave/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/acoustic_duct_wave.dir/build.make tests/CMakeFiles/acoustic_duct_wave.dir/build
.PHONY : acoustic_duct_wave/fast

#=============================================================================
# Target rules for targets named solid_gravity_hyperelastic

# Build rule for target.
solid_gravity_hyperelastic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_gravity_hyperelastic
.PHONY : solid_gravity_hyperelastic

# fast build rule for target.
solid_gravity_hyperelastic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_gravity_hyperelastic.dir/build.make tests/CMakeFiles/solid_gravity_hyperelastic.dir/build
.PHONY : solid_gravity_hyperelastic/fast

#=============================================================================
# Target rules for targets named fluid_initial_condition_mpi

# Build rule for target.
fluid_initial_condition_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_initial_condition_mpi
.PHONY : fluid_initial_condition_mpi

# fast build rule for target.
fluid_initial_condition_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_initial_condition_mpi.dir/build.make tests/CMakeFiles/fluid_initial_condition_mpi.dir/build
.PHONY : fluid_initial_condition_mpi/fast

#=============================================================================
# Target rules for targets named fluid_cavity

# Build rule for target.
fluid_cavity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_cavity
.PHONY : fluid_cavity

# fast build rule for target.
fluid_cavity/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_cavity.dir/build.make tests/CMakeFiles/fluid_cavity.dir/build
.PHONY : fluid_cavity/fast

#=============================================================================
# Target rules for targets named acoustic_duct_wave_mpi_scnsex

# Build rule for target.
acoustic_duct_wave_mpi_scnsex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acoustic_duct_wave_mpi_scnsex
.PHONY : acoustic_duct_wave_mpi_scnsex

# fast build rule for target.
acoustic_duct_wave_mpi_scnsex/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/acoustic_duct_wave_mpi_scnsex.dir/build.make tests/CMakeFiles/acoustic_duct_wave_mpi_scnsex.dir/build
.PHONY : acoustic_duct_wave_mpi_scnsex/fast

#=============================================================================
# Target rules for targets named fluid_cylinder_mpi_insimex

# Build rule for target.
fluid_cylinder_mpi_insimex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_cylinder_mpi_insimex
.PHONY : fluid_cylinder_mpi_insimex

# fast build rule for target.
fluid_cylinder_mpi_insimex/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_cylinder_mpi_insimex.dir/build.make tests/CMakeFiles/fluid_cylinder_mpi_insimex.dir/build
.PHONY : fluid_cylinder_mpi_insimex/fast

#=============================================================================
# Target rules for targets named solid_beam_bending_linearelastic

# Build rule for target.
solid_beam_bending_linearelastic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_beam_bending_linearelastic
.PHONY : solid_beam_bending_linearelastic

# fast build rule for target.
solid_beam_bending_linearelastic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_beam_bending_linearelastic.dir/build.make tests/CMakeFiles/solid_beam_bending_linearelastic.dir/build
.PHONY : solid_beam_bending_linearelastic/fast

#=============================================================================
# Target rules for targets named solid_rotation_Kirchhoff

# Build rule for target.
solid_rotation_Kirchhoff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_rotation_Kirchhoff
.PHONY : solid_rotation_Kirchhoff

# fast build rule for target.
solid_rotation_Kirchhoff/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_rotation_Kirchhoff.dir/build.make tests/CMakeFiles/solid_rotation_Kirchhoff.dir/build
.PHONY : solid_rotation_Kirchhoff/fast

#=============================================================================
# Target rules for targets named solid_rotation_mpi_shared_Kirchhoff

# Build rule for target.
solid_rotation_mpi_shared_Kirchhoff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_rotation_mpi_shared_Kirchhoff
.PHONY : solid_rotation_mpi_shared_Kirchhoff

# fast build rule for target.
solid_rotation_mpi_shared_Kirchhoff/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_rotation_mpi_shared_Kirchhoff.dir/build.make tests/CMakeFiles/solid_rotation_mpi_shared_Kirchhoff.dir/build
.PHONY : solid_rotation_mpi_shared_Kirchhoff/fast

#=============================================================================
# Target rules for targets named acoustic_pml_mpi

# Build rule for target.
acoustic_pml_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acoustic_pml_mpi
.PHONY : acoustic_pml_mpi

# fast build rule for target.
acoustic_pml_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/acoustic_pml_mpi.dir/build.make tests/CMakeFiles/acoustic_pml_mpi.dir/build
.PHONY : acoustic_pml_mpi/fast

#=============================================================================
# Target rules for targets named solid_gravity_linearelastic

# Build rule for target.
solid_gravity_linearelastic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solid_gravity_linearelastic
.PHONY : solid_gravity_linearelastic

# fast build rule for target.
solid_gravity_linearelastic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/solid_gravity_linearelastic.dir/build.make tests/CMakeFiles/solid_gravity_linearelastic.dir/build
.PHONY : solid_gravity_linearelastic/fast

#=============================================================================
# Target rules for targets named fluid_body_force_mpi

# Build rule for target.
fluid_body_force_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_body_force_mpi
.PHONY : fluid_body_force_mpi

# fast build rule for target.
fluid_body_force_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_body_force_mpi.dir/build.make tests/CMakeFiles/fluid_body_force_mpi.dir/build
.PHONY : fluid_body_force_mpi/fast

#=============================================================================
# Target rules for targets named fluid_cylinder_mpi

# Build rule for target.
fluid_cylinder_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fluid_cylinder_mpi
.PHONY : fluid_cylinder_mpi

# fast build rule for target.
fluid_cylinder_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/fluid_cylinder_mpi.dir/build.make tests/CMakeFiles/fluid_cylinder_mpi.dir/build
.PHONY : fluid_cylinder_mpi/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... acoustic_duct_wave"
	@echo "... acoustic_duct_wave_mpi"
	@echo "... acoustic_duct_wave_mpi_scnsex"
	@echo "... acoustic_pml"
	@echo "... acoustic_pml_mpi"
	@echo "... fluid_body_force_mpi"
	@echo "... fluid_cavity"
	@echo "... fluid_cylinder"
	@echo "... fluid_cylinder_insimex"
	@echo "... fluid_cylinder_mpi"
	@echo "... fluid_cylinder_mpi_insimex"
	@echo "... fluid_cylinder_mpi_scnsim"
	@echo "... fluid_gravity"
	@echo "... fluid_initial_condition_mpi"
	@echo "... fluid_pipe"
	@echo "... fluid_pipe_mpi"
	@echo "... fluid_plane_wall_driven_mpi_insim_supg"
	@echo "... fluid_pressure_driven"
	@echo "... fluid_pressure_driven_mpi_insim_supg"
	@echo "... fsi_benchmark"
	@echo "... fsi_cavity"
	@echo "... fsi_contact_model_mpi"
	@echo "... fsi_gravity"
	@echo "... fsi_gravity_mpi"
	@echo "... fsi_leaflet"
	@echo "... fsi_leaflet_mpi"
	@echo "... openifem"
	@echo "... solid_beam_bending_NeoHookean"
	@echo "... solid_beam_bending_linearelastic"
	@echo "... solid_beam_bending_mpi_NeoHookean"
	@echo "... solid_beam_bending_mpi_linearelastic"
	@echo "... solid_beam_bending_mpi_shared_NeoHookean"
	@echo "... solid_beam_bending_mpi_shared_linearelastic"
	@echo "... solid_gravity_hyperelastic"
	@echo "... solid_gravity_linearelastic"
	@echo "... solid_rotation_Kirchhoff"
	@echo "... solid_rotation_mpi_shared_Kirchhoff"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

